### ISSUE TITLE
"if" clause out of any functions

### ISSUE THREAD

**Issue by YonsiG** [cmstas/ZPrimeSnT#66]
in file fit_dimuon.C line 64, the "if" clause is outside of any functions so it gives compilation issues. Should it be moved into fitness()?

**Comment by mmasciov** [comment]
Yes, thank you. This will be fixed in my next update:
`bool doNotUseMultiPDF = ( useOnlyExponential || useOnlyPowerLaw || useOnlyBernstein ) ? true : false;`
